config/routes.rb
MolySite::Application.routes.draw do

  root to: 'pages#news'

  resources :events
  resources :venues do
    post 'approve'
    resources :sponsors do
      put 'move_up'
      put 'move_down'
    end
  end

  resources :users, only: [:index, :show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :memberships, only: [:create, :destroy]
  resources :mail_forwarder, only: :create

  resources :attachments, only: [:create, :new, :destroy]

  resources :games do
    resources :screenshots, only: [:show, :create, :destroy]
    resources :credits, only: [:create, :update, :destroy]
    post 'add_user'
    post 'remove_user'
    post 'upload_file'
    post 'remove_file'
  end
  resources :inspirations

  get '/user_file_uploads' => 'user_file_uploads#index'
  post '/user_file_uploads/upload' => 'user_file_uploads#upload'
  get '/attachments/reload/:id' => 'attachments#reload'

  match '/news' => 'pages#news'
  match '/about' => 'pages#about'
  match '/dashboard' => 'pages#dashboard'
  match '/host_resources' => 'pages#host_resources'
  match '/stats' => 'pages#stats'

  # Devise Routes
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/logout' => 'devise/sessions#destroy'
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
    resource :invitation,
      path: 'user/invitation',
      controller: 'invitations'
    resource :passwords,      only: [:new, :create, :edit, :update],  path: 'user/password',      controller: 'devise/passwords',       as: 'user_password'
    resource :confirmations,  only: [:new, :create, :show],           path: 'user/confirmation',  controller: 'devise/confirmations',   as: 'user_confirmation'
    resource :unlocks,        only: [:new, :create, :show],           path: 'user/unlock',        controller: 'devise/unlocks',         as: 'user_unlock'
  end

  # Archive Link Redirection
  match "/display.php" => redirect("http://archive.molyjam.com")
end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base
  attr_accessible :quote, :source
end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController
  load_and_authorize_resource
 
  def index
    if(params[:show] == "all")
      @inspirations = Inspiration.all
      @mode = :all
    else
      @inspirations = Inspiration.find(:all, :order => "id asc", :limit => 22)
      @mode = :some
    end

    logger.info "#{params[:action]}"

    respond_to do |format|
      format.html { render layout: "inspiration" }
    end
  end

  def show
    @inspiration = Inspiration.find(params[:id])

    respond_to do |format|
      format.html { render layout: "inspiration" }
    end
  end

  def new
    @inspiration = Inspiration.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @inspiration = Inspiration.find(params[:id])
  end

  def create
    @inspiration = Inspiration.new(params[:inspiration])

    respond_to do |format|
      if @inspiration.save
        format.html { redirect_to @inspiration, notice: 'Inspiration was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @inspiration = Inspiration.find(params[:id])

    respond_to do |format|
      if @inspiration.update_attributes(params[:inspiration])
        format.html { redirect_to @inspiration, notice: 'Inspiration was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @inspiration = Inspiration.find(params[:id])
    @inspiration.destroy

    respond_to do |format|
      format.html { redirect_to inspirations_url }
    end
  end
end

app/helpers/inspirations_helper.rb
module InspirationsHelper
end

app/views/inspirations/_form.html.erb
<%= form_for(@inspiration) do |f| %>
  <% if @inspiration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspiration.errors.count, "error") %> prohibited this inspiration from being saved:</h2>

      <ul>
      <% @inspiration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_area :quote %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspirations/edit.html.erb
<h1>Editing inspiration</h1>

<%= render 'form' %>

<%= link_to 'Show', @inspiration %> |
<%= link_to 'Back', inspirations_path %>

app/views/inspirations/index.html.erb
<% content_for :body do %>
  <body id="list">
<% end %>

<div class="page">

  <%= link_to "Molyjam 2013", news_path, class: 'molyjam' %>
  
  <% @inspirations.shuffle.each do |inspiration| %>
    <div class="contain">
      <div class="molybox">
        <%= link_to inspiration.quote.to_s, inspiration, class: "molyquote"  %>
        <div class="molycite">
          <%= link_to "Peter Molyneux", inspiration.source %>
        </div>
      </div>
    </div>
  <% end %>

  <div id="nav">
    <%= link_to "show curated wisdom", inspirations_path if @mode == :all %>
    <%= link_to "list all wisdom", inspirations_path(show: 'all') if @mode == :some %>
  </div>
</div>

app/views/inspirations/new.html.erb
<h1>New inspiration</h1>

<%= render 'form' %>

<%= link_to 'Back', inspirations_path %>

app/views/inspirations/show.html.erb
<% content_for :body do %>
  <body id="single">
<% end %>

<div class="page">

  <%= link_to "Molyjam 2013", news_path, class: 'molyjam' %>
  
    <div class="contain">
      <div class="molybox">
        <%= link_to @inspiration.quote.to_s, @inspiration, class: "molyquote"  %>
        <div class="molycite">
          <%= link_to "Peter Molyneux", @inspiration.source %>
        </div>
      </div>
    </div>

  <div id="nav">
    <% #link_to "Tweet this wisdom", @inspiration &#8226;  %> 
    <%= link_to "show curated wisdom", inspirations_path %> &#8226; 
    <%= link_to "list all wisdom", inspirations_path(show: 'all') %>
  </div>
</div>