config/routes.rb
MolySite::Application.routes.draw do

  root to: 'pages#news'

  resources :events
  resources :venues do
    post 'approve'
    resources :sponsors do
      put 'move_up'
      put 'move_down'
    end
  end

  resources :users, only: [:index, :show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :memberships, only: [:create, :destroy]
  resources :mail_forwarder, only: :create

  resources :attachments, only: [:create, :new, :destroy]

  resources :games do
    resources :screenshots, only: [:show, :create, :destroy]
    resources :credits, only: [:create, :update, :destroy]
    post 'add_user'
    post 'remove_user'
    post 'upload_file'
    post 'remove_file'
  end
  resources :inspirations

  get '/user_file_uploads' => 'user_file_uploads#index'
  post '/user_file_uploads/upload' => 'user_file_uploads#upload'
  get '/attachments/reload/:id' => 'attachments#reload'

  match '/news' => 'pages#news'
  match '/about' => 'pages#about'
  match '/dashboard' => 'pages#dashboard'
  match '/host_resources' => 'pages#host_resources'
  match '/stats' => 'pages#stats'

  # Devise Routes
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/logout' => 'devise/sessions#destroy'
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
    resource :invitation,
      path: 'user/invitation',
      controller: 'invitations'
    resource :passwords,      only: [:new, :create, :edit, :update],  path: 'user/password',      controller: 'devise/passwords',       as: 'user_password'
    resource :confirmations,  only: [:new, :create, :show],           path: 'user/confirmation',  controller: 'devise/confirmations',   as: 'user_confirmation'
    resource :unlocks,        only: [:new, :create, :show],           path: 'user/unlock',        controller: 'devise/unlocks',         as: 'user_unlock'
  end

  # Archive Link Redirection
  match "/display.php" => redirect("http://archive.molyjam.com")
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :memberships
	has_many :users, :through => :memberships

	attr_accessible :description, :name
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def show
    @group = Group.find(params[:id])
    @memberships = Membership.where(group_id: @group.id)
  end

  def edit
    @group = Group.find(params[:id])
    @memberships = Membership.where(group_id: @group.id)
  end

  def update
    @group = Group.find(params[:id])
    if(@group.update_attributes(params[:group]))
      redirect_to :action => 'show', :id => @group
  	else
      @memberships = Membership.where(group_id: @group.id)
      render :action => 'edit'
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= form_for(@group, :url => {:action => "update"}, :html => {:method => :put }) do |f| %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name, :autofocus => true %></div>

  <div><%= f.label :description %><br />
  <%= f.text_area :description %></div>

  <div><%= f.submit "Update", class: "btn" %></div>
<% end %>

<%= link_to "Back", :back, class: "btn" %>

app/views/groups/show.html.erb
<h1><% @group.name %></h1>
<p><% @group.description %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Twitter</th>
      <th>Rank</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @group.memberships.each do |membership| %>
      <tr>
        <td><%= membership.user.name %></td>
        <td>@<%= membership.user.twitter_username %></td>
        <td><%= Membership::ROLES.invert[membership.role].to_s.titleize %></td>
        <td><%= link_to 'Remove', membership_path(membership), :confirm => 'Are you sure?', :method => :delete if can? :destroy, membership %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
      <%if can? :create, Membership %>
        <tr>
          <%= form_for Membership.new do |f| %>
            <td>Username</td>
            <td colspan="2"><%= text_field :user, :username %></td>
            <%= f.hidden_field :group_id, value: @group.id %>
            <%= f.hidden_field :role, value: Membership::ROLES[:officer] %>
            <td><%= f.submit "Add Host", class: "btn" %></td>
          <% end %>
        </tr>
        <% end %>
      </tfoot>
</table>

<%= link_to "Back", :back, class: "btn" %>