config/routes.rb
MolySite::Application.routes.draw do

  root to: 'pages#news'

  resources :events
  resources :venues do
    post 'approve'
    resources :sponsors do
      put 'move_up'
      put 'move_down'
    end
  end

  resources :users, only: [:index, :show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :memberships, only: [:create, :destroy]
  resources :mail_forwarder, only: :create

  resources :attachments, only: [:create, :new, :destroy]

  resources :games do
    resources :screenshots, only: [:show, :create, :destroy]
    resources :credits, only: [:create, :update, :destroy]
    post 'add_user'
    post 'remove_user'
    post 'upload_file'
    post 'remove_file'
  end
  resources :inspirations

  get '/user_file_uploads' => 'user_file_uploads#index'
  post '/user_file_uploads/upload' => 'user_file_uploads#upload'
  get '/attachments/reload/:id' => 'attachments#reload'

  match '/news' => 'pages#news'
  match '/about' => 'pages#about'
  match '/dashboard' => 'pages#dashboard'
  match '/host_resources' => 'pages#host_resources'
  match '/stats' => 'pages#stats'

  # Devise Routes
  devise_for :users, :skip => [:sessions, :registrations, :passwords, :confirmations, :unlocks]
  as :user do
    get '/login' => 'devise/sessions#new', :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get '/logout' => 'devise/sessions#destroy'
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
    resource :invitation,
      path: 'user/invitation',
      controller: 'invitations'
    resource :passwords,      only: [:new, :create, :edit, :update],  path: 'user/password',      controller: 'devise/passwords',       as: 'user_password'
    resource :confirmations,  only: [:new, :create, :show],           path: 'user/confirmation',  controller: 'devise/confirmations',   as: 'user_confirmation'
    resource :unlocks,        only: [:new, :create, :show],           path: 'user/unlock',        controller: 'devise/unlocks',         as: 'user_unlock'
  end

  # Archive Link Redirection
  match "/display.php" => redirect("http://archive.molyjam.com")
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :event
  belongs_to :venue
  belongs_to :group
  has_many :users, :through => :group
  has_many :screenshots, dependent: :destroy
  has_many :credits, dependent: :destroy

  attr_accessible :event_id, :group_id, :inspiration, :name, :venue_id, :description, :directions, :play_in_browser_url,
   :play_in_browser_type, :android_url, :ios_url, :genre, :engine, :windows_file, :mac_file, :linux_file, :traditional_file

  mount_uploader :windows_file, FileUploader
  mount_uploader :mac_file, FileUploader
  mount_uploader :linux_file, FileUploader
  mount_uploader :traditional_file, FileUploader

  after_create :create_group

  def create_group
    self.group_id = Group.create(name: self.name).id
    self.save
    true
  end

  def add_user(user, role = :member)
    Membership.set(user.id, self.group_id, role)
    Membership.set(user.id, Group.where(name: "Jammers").first)
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource

  def index
    @games = Game.all.shuffle

    respond_to do |format|
      format.html
    end
  end

  def show
    @game = Game.find(params[:id])

    @game.windows_file.success_action_status = "201"
    @game.mac_file.success_action_status = "201"
    @game.linux_file.success_action_status = "201"
    @game.traditional_file.success_action_status = "201"

    respond_to do |format|
      format.html
    end
  end

  def index
    if params[:event_id].nil?
      @games = Game.all.shuffle
    else
      @games = Game.where(event_id: params[:event_id]).shuffle
    end
    
    respond_to do |format|
      format.html
    end
  end

  def new
    @game = Game.new

    respond_to do |format|
      format.html
    end
  end

  def create
    return render action: "new", alert: 'Invalid game name!' if params[:game][:name].to_s.empty?
    @game = Game.new(params[:game])
  
    respond_to do |format|
      if @game.save
        Credit.create!(user_id: current_user.id, game_id: @game.id)
        @game.add_user(current_user, :founder)
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
      else
        format.html { render action: "new", alert: 'Something broke!' }
      end
    end
  end

  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.json { head :ok }
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
      else
        format.json { render json: @game.errors.full_messages, status: :uprocessable_entity}
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
    end
  end

  def upload_file
    @game = Game.find(params[:game_id])

    @game.windows_file.key = params[:key] if params[:key] =~ /windows_file/
    @game.mac_file.key = params[:key] if params[:key] =~ /mac_file/
    @game.linux_file.key = params[:key] if params[:key] =~ /linux_file/
    @game.traditional_file.key = params[:key] if params[:key] =~ /traditional_file/

    @game.save

    redirect_to @game, notice: 'file was successfully updated.'
  end

  def remove_file
    @game = Game.find(params[:game_id])

    @game.remove_windows_file! if params[:game][:file] == "windows_file"
    @game.remove_mac_file! if params[:game][:file] == "mac_file"
    @game.remove_linux_file! if params[:game][:file] == "linux_file"
    @game.remove_traditional_file! if params[:game][:file] == "traditional_file"

    @game.save

    redirect_to @game, notice: 'file was successfully removed.'
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_article.html.erb
<article>

  <% if can?(:edit, @game) %>
  <div class="admin-insert">
    <p>To edit any of your game data, simply click on the text you wish to edit. (You can even change the name of your game)</p>
    <p>To delete your game, <%= link_to "click here", game_path(@game), :method => :delete, :confirm => "Are you sure?" %></p>
  </div>
  <% end %>

  <% if !@game.description.to_s.empty? || can?(:edit, @game) %>
  <section>
    <header>
      <h2>About</h2>
    </header>
    <p><%= best_in_place_if can?(:edit, @game),  @game, :description, type: :textarea, nil: "click here to add a description" %></p>
  </section>
  <hr />
  <% end %>

  <%= render 'screenshots' %>

  <%= render 'credits' %>

  <% if !@game.directions.to_s.empty? || can?(:edit, @game) %>
  <section>
    <header>
      <h2>Directions</h2>
    </header>
    <p><%= best_in_place_if can?(:edit, @game),  @game, :directions, type: :textarea, nil: "click here to add a directions" %></p>
  </section>
  <hr />
  <% end %>

</article>

app/views/games/_create.html.erb
<% if can? :create, Game %>
<div style="padding: 1em; background-color: #555;">
	<h4>Ready to share your game with the world?</h4>

	<%= form_for Game.new do |f| %>
	<p>Whats your game called? <%= f.text_field :name %></p>
	<%= f.submit "Create!", class: "button" %>
	<% end %>
</div>
<% end %>

app/views/games/_credits.html.erb
<section>
  <h2>Credits</h2>
  <table class="credits">
    <tbody>

      <% @game.credits.each do |credit| %>
      <tr>
        <td class="name"><%= credit.user.name %></td>
        <td class="twitter">
          <%= link_to "@#{credit.user.twitter_username}", "http://www.twitter.com/#{credit.user.twitter_username}" unless credit.user.twitter_username.to_s.empty? %></td>
        <td class="name"><%= best_in_place_if can?(:edit, credit), credit, :title, path: game_credit_path(@game.id, credit.id), nil: "click here to add a title" %></title>

        <% if can?(:destroy, credit) && credit.user.memberships.where(group_id: @game.group_id).first.role < Membership::ROLES[:founder] %>
        <td class="admin-insert">
          <%= link_to "Remove", game_credit_path(@game.id, credit.id), :method => :delete, :confirm => "Are you sure?" %>
        </td>
        <% end %>

      </tr>
      <% end %>

    </tbody>

    <% if can? :edit, @game %>
    <tfoot>
        <% if can? :create, User %>
        <%= form_for :credit, url: game_credits_path(@game) do |f| %>
        <tr>
          <td class="admin-insert">Name:</td>
          <td class="admin-insert" colspan="2"><%= text_field :user, :name %></td>
        </tr>
        <tr>
          <td class="admin-insert">Email:</td>
          <td class="admin-insert" colspan="2"><%= email_field :user, :email %></td>
        </tr>
        <tr>
          <td class="admin-insert">Title:</td>
          <td class="admin-insert" colspan="2"><%= f.text_field :title %></td>
        </tr>
        <tr>
          <td class="admin-insert" colspan="3"><%= f.submit "Add User", class: "btn" %></td>
        </tr>
        <% end %>
        <% else %>
        <td colspan="3">Note: Only the orginal creator of the game page can edit users</td>
        <% end %>
      </tr>
    </tfoot>
    <% end %>

  </table>

</section>
<hr/>

app/views/games/_form_files.html.erb
<p>Acceptable file formats are zip, tar, gz. Max file size is 500mb.</p>

<div id="windows-file" data-url="<%= game_upload_file_url(@game) %>">
  <hr />
  <% if @game.windows_file.to_s.empty? %>
  <%= direct_upload_form_for @game.windows_file, html: {id: "new_windows_file_uploader"} do |f| %>
  <%= f.label :windows_file, "Windows: " %>
  <%= f.file_field :windows_file, use_action_status: true, style: "width: 100%", name: "game[windows_file]" %>
  <% end %>
  <% else %>
  <%= form_for @game, url: game_remove_file_path(@game), method: "post" do |f| %>
  <%= f.label :windows_file, "Windows: " %>
  <%= f.hidden_field :file, value: "windows_file" %>
  <%= f.submit "Delete" %>
  <% end %>
  <% end %>
</div>

<div id="mac-file" data-url="<%= game_upload_file_url(@game) %>">
  <hr />
  <% if @game.mac_file.to_s.empty? %>
  <%= direct_upload_form_for @game.mac_file, html: {id: "new_mac_file_uploader"} do |f| %>
  <%= f.label :mac_file, "Mac: " %>
  <%= f.file_field :mac_file, use_action_status: true, style: "width: 100%", name: "game[mac_file]" %>
  <% end %>
  <% else %>
  <%= form_for @game, url: game_remove_file_path(@game), method: "post" do |f| %>
  <%= f.label :mac_file, "Mac: " %>
  <%= f.hidden_field :file, value: "mac_file" %>
  <%= f.submit "Delete" %>
  <% end %>
  <% end %>
</div>

<div id="linux-file" data-url="<%= game_upload_file_url(@game) %>">
  <hr />
  <% if @game.linux_file.to_s.empty? %>
  <%= direct_upload_form_for @game.linux_file, html: {id: "new_linux_file_uploader"} do |f| %>
  <%= f.label :linux_file, "Linux: " %>
  <%= f.file_field :linux_file, use_action_status: true, style: "width: 100%", name: "game[linux_file]" %>
  <% end %>
  <% else %>
  <%= form_for @game, url: game_remove_file_path(@game), method: "post" do |f| %>
  <%= f.label :linux_file, "Linux: " %>
  <%= f.hidden_field :file, value: "linux_file" %>
  <%= f.submit "Delete" %>
  <% end %>
  <% end %>
</div>

<div id="traditional-file" data-url="<%= game_upload_file_url(@game) %>">
  <hr />
  <% if @game.traditional_file.to_s.empty? %>
  <%= direct_upload_form_for @game.traditional_file, html: {id: "new_traditional_file_uploader"} do |f| %>
  <%= f.label :traditional_file, "Traditional: " %>
  <%= f.file_field :traditional_file, use_action_status: true, style: "width: 100%", name: "game[traditional_file]" %>
  <% end %>
  <% else %>
  <%= form_for @game, url: game_remove_file_path(@game), method: "post" do |f| %>
  <%= f.label :traditional_file, "Traditional: " %>
  <%= f.hidden_field :file, value: "traditional_file" %>
  <%= f.submit "Delete" %>
  <% end %>
  <% end %>
</div>

<script id="template-upload-windows-files" type="text/x-tmpl">
<div class="upload" id="upload-windows">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<script id="template-upload-mac-files" type="text/x-tmpl">
<div class="upload" id="upload-mac">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<script id="template-upload-linux-files" type="text/x-tmpl">
<div class="upload" id="upload-linux">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<script id="template-upload-traditional-files" type="text/x-tmpl">
<div class="upload" id="upload-traditional">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/games/_header.html.erb
<%
if @game.screenshots.empty?
  image_path = asset_path "pixel-bg.jpg"
else
  image_path = @game.screenshots.shuffle.first.image_url
end
%>

<% content_for :header do %>

<div id="header-image">
  <svg id="svg-image-blur" xmlns="http://www.w3.org/2000/svg" version="1.1" width="100%" height="100%">
    <defs>
      <filter id="blur-effect-1">
        <feGaussianBlur stdDeviation="2"></feGaussianBlur>
      </filter>
    </defs>
    <image xlink:href="<%= image_path%>" id="css-filter-blur" class="stretch" alt="" width="100%" height="100%" filter="url(#blur-effect-1)" preserveAspectRatio="xMidYMid slice"></image>
  </svg>
</div>

<% end %>
<h1 id="gameTitle" class="game-title"><%= best_in_place_if can?(:edit, @game), @game, :name, type: :input %></h1>

app/views/games/_screenshots.html.erb
<section>
  <div id="screenshots">
    <% @game.screenshots.each do |screenshot| %>
    <% @screenshot = screenshot %>
    <%= render 'screenshots/show_article' %>
    <% end %>
  </div>
  
  <% if can? :edit, @game %>
  <div class="admin-insert">
  	<%= render 'screenshots/form' %>
  </div>
  <% end %>

</section>
<hr/>

app/views/games/index.html.erb
<% title "MolyJam - Games" %>
<%= render 'create' %>
<div id="big-ass-game-list">
  <div class="gamelist-filters">

    <div class="dropdown-btn-container">
      <div data-dropdown="#dropdown-platform" class="btn-filter">
        <span class="dropdown-label">PLATFORM</span>
        <span class="dropdown-selected" id="current-platform">All</span>
      </div>
      <div data-dropdown="#dropdown-genre" class="btn-filter">
        <span class="dropdown-label">GENRE</span>
        <span class="dropdown-selected" id="current-genre">All</span>
      </div>
      <div data-dropdown="#dropdown-location" class="btn-filter">
        <span class="dropdown-label">LOCATION</span>
        <span class="dropdown-selected" id="current-location">All</span>
      </div>
       
      <%= image_tag "games/sort-grid.png", id: "dropdown-grid-button", class: "dropdown-sort active" %>
      <%= image_tag "games/sort-list.png", id: "dropdown-list-button", class: "dropdown-sort inactive" %>
      <div  class="dropdown-search">
        <input type="text" class="search" placeholder="Search Filtered Results">
      </div>
    </div>

    <div id="dropdown-platform" class="dropdown dropdown-tip">
      <ul class="dropdown-menu">
        <li><a class="dropdown-platform-link" id="platform-all">All</a></li>
        <li><a class="dropdown-platform-link" id="windows">Windows</a></li>
        <li><a class="dropdown-platform-link" id="mac">Mac OS X</a></li>
        <li><a class="dropdown-platform-link" id="linux">Linux</a></li>
        <li><a class="dropdown-platform-link" id="flash">Flash (Browser)</a></li>
        <li><a class="dropdown-platform-link" id="unity">Unity (Browser)</a></li>
        <li><a class="dropdown-platform-link" id="html">HTML 5 (Browser)</a></li>
        <li><a class="dropdown-platform-link" id="ios">iOS (Mobile)</a></li>
        <li><a class="dropdown-platform-link" id="android">Android (Mobile)</a></li>
        <li><a class="dropdown-platform-link" id="traditional">Traditional</a></li>
      </ul>
    </div>

    <div id="dropdown-genre" class="dropdown dropdown-tip">
      <ul class="dropdown-menu">
        <li><a class="dropdown-genre-link" id="genre-all">All</a></li>
        <% Game.select(:genre).map(&:genre).uniq.each do |genre| %>
          <li><a class="dropdown-genre-link" id="<%= genre.to_s %>"><%= genre.to_s %></a></li>
        <% end %>
      </ul>
    </div>

    <div id="dropdown-location" class="dropdown dropdown-tip">
      <ul class="dropdown-menu">
        <li><a class="dropdown-location-link" id="location-all">All</a></li>
        <% Venue.all.each do |venue| %>
          <li><a class="dropdown-location-link" id="<%= venue.display_name %>"><%= venue.display_name %></a></li>
        <% end %>
      </ul>
    </div>

  </div>

  <div id="game-list-toggle" class="layout-grid">
    <div id="game-list">
      <ul class="list gamelist">
        <% @games.each do |game| %>
        <%
        unless game.screenshots.empty?
          game_screenshot = game.screenshots.shuffle.first.image_url(:thumb_grid)
        else
          game_screenshot = asset_path "pixel-bg.jpg"
        end
        %>

        <li>

          <% unless game.windows_file.to_s.empty? %><span class="windows" style="display:none">windows</span><% end %>
          <% unless game.mac_file.to_s.empty? %><span class="mac" style="display:none">mac</span><% end %>
          <% unless game.linux_file.to_s.empty? %><span class="linux" style="display:none">linux</span><% end %>
          <% unless game.traditional_file.to_s.empty? %><span class="traditional" style="display:none">traditional</span><% end %>

          <% unless game.play_in_browser_url.to_s.empty? %>
          <% if game.play_in_browser_type == "flash" %><span class="flash" style="display:none">flash</span><% end %>
          <% if game.play_in_browser_type == "html" %><span class="html" style="display:none">html</span><% end %>
          <% if game.play_in_browser_type == "unity" %><span class="unity" style="display:none">unity</span><% end %>
          <% end %>

          <% unless game.ios_url.to_s.empty? %><span class="ios" style="display:none">ios</span><% end %>
          <% unless game.android_url.to_s.empty? %><span class="android" style="display:none">android</span><% end %>


          <div class="gamelist-container"> 
            <%= link_to game_path(game) do %>
              <div class="list-screenshot-top" style="background-image: url(<%= game_screenshot %>)"></div>
            <% end %>
            <div class="list-body-container">
              <div class="list-body-grid">
                <h4><%= link_to game_path(game) do %><span class="name"><%= game.name %></span><% end %></h4>
                <h5><span class="genre"><%= game.genre %></span></h5>
                <div class="description"><%= truncate game.description, length: 140 %></div>
                <hr/>

                <%= image_tag "games/platforms/windows.png", class: "list-platform" unless game.windows_file.to_s.empty? %>
                <%= image_tag "games/platforms/mac.png", class: "list-platform" unless game.mac_file.to_s.empty? %>
                <%= image_tag "games/platforms/linux.png", class: "list-platform" unless game.linux_file.to_s.empty? %>
                <%= image_tag "games/platforms/traditional.png", class: "list-platform" unless game.traditional_file.to_s.empty? %>

                <% unless game.play_in_browser_url.to_s.empty? %>
                <%= image_tag "games/platforms/flash.png", class: "list-platform" if game.play_in_browser_type == "flash"%>
                <%= image_tag "games/platforms/html5.png", class: "list-platform" if game.play_in_browser_type == "html"%>
                <%= image_tag "games/platforms/unityweb.png", class: "list-platform" if game.play_in_browser_type == "unity"%>
                <% end %>

                <%= image_tag "games/platforms/ios.png", class: "list-platform" unless game.ios_url.to_s.empty? %>
                <%= image_tag "games/platforms/android.png", class: "list-platform" unless game.android_url.to_s.empty? %>

                <% unless game.venue.nil? %>
                <h5><span class="location-filler">Made in </span><span class="location"><%= game.venue.display_name %></span></h5>
                <% end %>
              </div>
              <div class="list-body-list">
                <%= image_tag "games/platforms/windows.png", class: "list-platform" unless game.windows_file.to_s.empty? %>
                <%= image_tag "games/platforms/mac.png", class: "list-platform" unless game.mac_file.to_s.empty? %>
                <%= image_tag "games/platforms/linux.png", class: "list-platform" unless game.linux_file.to_s.empty? %>
                <%= image_tag "games/platforms/traditional.png", class: "list-platform" unless game.traditional_file.to_s.empty? %>

                <% unless game.play_in_browser_url.to_s.empty? %>
                <%= image_tag "games/platforms/flash.png", class: "list-platform" if game.play_in_browser_type == "flash"%>
                <%= image_tag "games/platforms/html5.png", class: "list-platform" if game.play_in_browser_type == "html"%>
                <%= image_tag "games/platforms/unityweb.png", class: "list-platform" if game.play_in_browser_type == "unity"%>
                <% end %>

                <%= image_tag "games/platforms/ios.png", class: "list-platform" unless game.ios_url.to_s.empty? %>
                <%= image_tag "games/platforms/android.png", class: "list-platform" unless game.android_url.to_s.empty? %>

                <span class="list-game-info">
                  <h4><%= link_to game_path(game) do %><span class="name"><%= game.name %></span><% end %></h4>
                  <h5>
                    <span class="genre"><%= game.genre %></span>
                    <% unless game.venue.nil? %>
                    <span class="location-filler">Made in <span class="location"><%= game.venue.display_name %></span>
                    <% end %>
                  </h5>
                  <hr/>
                  <div class="description"><%= truncate game.description, length: 140 %></div>
                </span>
              </div>
            </div>
            <%= link_to game_path(game) do %>
            <div class="list-screenshot-bottom" style="background-image: url(<%= game_screenshot %>)"></div>
            <% end %>
          </div>
        </li>
        <% end %>
        
      </div>
    </div>
  </div>
</div>
    
       
   
    

app/views/games/new.html.erb
<% if can? :create, Game %>
<div style="padding: 1em; background-color: #555;">
	<h4>Ready to share your game with the world?</h4>

	<%= form_for Game.new do |f| %>
	<p>Whats your game called? <%= f.text_field :name %></p>

	<p>When did you create your game? <br />
	<%= f.collection_select(:event_id, Event.all, :id, :name) %></p>
	<%= f.submit "Create!", class: "button" %>
	<% end %>
</div>
<% end %>

app/views/games/show.html.erb
<% title "MolyJam - #{@game.name}" %>
<%= render 'header' %>
<%= render 'article' %>

<div class="download-area">
  <%= link_to @game.windows_file_url.to_s do %><aside class="download-link"><%= image_tag "games/platforms/windows.png" %><p>Download</p></aside><% end unless @game.windows_file_url.to_s.empty? %>
  <%= link_to @game.mac_file_url.to_s do %><aside class="download-link"><%= image_tag "games/platforms/mac.png" %><p>Download</p></aside></a><% end unless @game.mac_file_url.to_s.empty? %>
  <%= link_to @game.linux_file_url.to_s do %><aside class="download-link"><%= image_tag "games/platforms/linux.png" %><p>Download</p></aside></a><% end unless @game.linux_file_url.to_s.empty? %>
  <%= link_to @game.traditional_file_url.to_s do %><aside class="download-link"><%= image_tag "games/platforms/traditional.png" %><p>Download</p></aside></a><% end unless @game.traditional_file_url.to_s.empty? %>

  <%= link_to @game.play_in_browser_url do %>
  <aside class="download-link">
    <%= image_tag "games/platforms/flash.png" if @game.play_in_browser_type == "flash"%>
    <%= image_tag "games/platforms/html5.png" if @game.play_in_browser_type == "html"%>
    <%= image_tag "games/platforms/unityweb.png" if @game.play_in_browser_type == "unity"%>
    <p>Play in Browser</p>
  </aside>
  <% end unless @game.play_in_browser_url.to_s.empty? %>

  <%= link_to @game.ios_url do %><aside class="download-link"><%= image_tag "games/platforms/ios.png" %><p>Find on App Store</p></aside></a><% end unless @game.ios_url.to_s.empty? %>
  <%= link_to @game.android_url do %><aside class="download-link"><%= image_tag "games/platforms/android.png" %><p>Find on Google Play</p></aside></a><% end unless @game.android_url.to_s.empty? %>


  <% if can? :edit, @game %>
  <aside>
    <%= render 'form_files' %>

    <div id="browser_urls">
    <hr />
    <%= form_for(@game) do |f| %>
    <div class="field">
      <%= f.label :play_in_browser_url, "Play in Browser URL" %>
      <%= f.url_field :play_in_browser_url %>
    </div>
    <div class="field">
      <%= f.label :play_in_browser_type %>
      <%= f.select(:play_in_browser_type, [["Flash", "flash"], ["HTML 5", "html"], ["Unity Web Player", "unity"]]) %>
    </div>
    <div class="field">
      <%= f.label :android_url, "Android Marketplace URL" %>
      <%= f.url_field(:android_url) %>
    </div>
    <div class="field">
      <%= f.label :ios_url, "iOS App Store URL" %>
      <%= f.url_field(:ios_url) %>
    </div>
    <br />
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
  </aside>
  <% end %>
</div>

<div class="no-bg">
  <aside>
    <h3>Information</h3>
    <p>
      <% if can? :edit, @game %>
        <% 
          locations = Array.new 
          Venue.all.each{ |venue| locations.push [venue.id, venue.display_name]}
        %>
        <span class="info-category">Genre: </span> <span class="info-fill" id="genreName"><%= best_in_place_if can?(:edit, @game), @game, :genre %></span><br/>
        <span class="info-category">Engine / Tool: </span> <span class="info-fill" id="gameEngine"><%= best_in_place_if can?(:edit, @game), @game, :engine %></span><br/>
        <span class="info-category">Location: </span><span class="info-fill" id="gameLocation"><%= best_in_place_if can?(:edit, @game), @game, :venue_id, type: :select, collection: locations %></p></span>
      <% else %>
        <% unless @game.genre.to_s.empty? %><span class="info-category">Genre: </span> <span class="info-fill" id="genreName"><%= @game.genre.to_s %></span><br/><% end %>
        <% unless @game.engine.to_s.empty? %><span class="info-category">Engine / Tool: </span> <span class="info-fill" id="gameEngine"><%= @game.engine.to_s %></span><br/><% end %>
        <% unless @game.venue.to_s.empty? %><span class="info-category">Location: </span><span class="info-fill" id="gameLocation"><%= link_to @game.venue.display_name, venue_path(@game.venue) %></span><% end %>
      <% end %>
    </p>
  </aside>

  <% if !@game.inspiration.to_s.empty? || can?(:edit, @game) %>
    <aside>
      <h3>Inspiration</h3>
      <p><%= best_in_place_if can?(:edit, @game), @game, :inspiration, type: :textarea, ok_button: "Save", cancel_button: "Cancel", nil: "click here to add the inspirating quote" %></p>
    </aside>
  <% end %>

</div>